### ISSUE TITLE
Update timber vignette once everything is done

### ISSUE THREAD

**Issue by kodesiba** [atorus-research/timber#23]

**Comment by bms63** [comment]
oohhhh i want to do this or at least help with it!

**Comment by kodesiba** [comment]
@bms63 dev should be fully featured for this release.  If you want to branch off and update the vignette you can go for it.  I can also look next week.  I think the example we have in there might be a bit long at this point so I propose removing the image from the vignette since it's so big at this point it almost looks comical in the middle of it

**Comment by kodesiba** [comment]
change timber vignette to include basic example and move scripting and execution pieces to execution vignette
