### ISSUE TITLE
Neccessary Feature : please include last run/ran code in the log file

### ISSUE THREAD

**Issue by sv8462** [atorus-research/timber#28]
Hi All,

I am surprised that its not implemented yet. Its a must have component in clinical industry for audit purposes. Can you guys please update the package to include run/session ran code in the log file? For example, if I run the below code, then, the log file should contain the below code.

Code:
iris %>% pivot_longer(c(Sepal.Length, Petal.Length))

Perhaps , it can be achieved with base package sink() function. 

Thanks.
Shiva.

**Comment by bms63** [comment]
How come you wouldn't just include the .R file that has that code with the log file?  Like they would be paired together.

The log file could get awfully verbose if we include code in the log file.

**Comment by kodesiba** [comment]
The main purpose of this package was to capture what was happening but not the code run.  This provides anyone what happened during execution of the code and what environment the code was run in but we purposefully excluded pieces like this as they are unnecessary to a log file if you are submitting programs as is the industry standard.   I will echo what @bms63 said above as this would make the log unnecessarily long and hard to read (like the SAS log is).

**Comment by kodesiba** [comment]
While this issue has been closed, we are exploring add some sort of hashed value of the file that was executed for traceability of the log/file relationship. See #29
