### ISSUE TITLE
Bug: Rival Package Name

### ISSUE THREAD

**Issue by bms63** [atorus-research/timber#62]
### What happened?

There is already a timber package on CRAN :(

**Comment by mstackhouse** [comment]
Are CRAN packages case sensitive? I technically think {timber} could co-exist because the one on CRAN has a capital R. 

For example, this link works: 
- https://cran.r-project.org/package=timbeR

But this does not:
- https://cran.r-project.org/package=timber

**Comment by bms63** [comment]
Awesome!!  Good news.

@nicholas-masel did send me inflatable turnstiles links for {record} if we went that route.

**Comment by bms63** [comment]
![image](https://user-images.githubusercontent.com/10111024/168650019-697df190-f418-4995-82a5-c50f3712c074.png)

**Comment by kodesiba** [comment]
Will be updating the package name to timberland
