### ISSUE TITLE
Add stdout logging support

### ISSUE THREAD

**Issue by nicholas-masel** [atorus-research/timber#7]
I see run_safetly_n_quietly() is logging warnings and errors, but could this capture stdout as well?  If the concern is length or that this is not wanted, could it be an option to opt in and out of, or written last.

**Comment by kodesiba** [comment]
this is very much in the works, we actually have most of the code for it we just need to add it to the Errors/Warnings section and add a toggle for if the user wants it included or not

**Comment by nicholas-masel** [comment]
If output is going to come directly from purrr::quietly, is there any concern w/users understaning they must use print statements for this to make it in the log?

Ex.
``` r
head(mtcars, n = 1) 
#>           mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4

a <- purrr::quietly(function(){
   head(mtcars, n = 1) 
   1
   })
a()$output
#> [1] ""

b <- purrr::quietly(function(){
   print(head(mtcars, n = 1) )
   1
})
b()$output
#> [1] "          mpg cyl disp  hp drat   wt  qsec vs am gear carb\nMazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4"
```

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
